Travis: Nix-style local builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,87 +1,57 @@
-# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
-language: c
+# Inspired by
+# https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml_2.hs
+
 sudo: false
+language: c
 
-# cache:
-#   directories:
-#     - $HOME/.cabsnap
-#     - $HOME/.cabal/packages
-
-# before_cache:
-#   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-#   - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+cache:
+  directories:
+    - $HOME/.cabal
 
 matrix:
   include:
-    - env: CABALVER=1.22 GHCVER=7.10.3
-      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=7.10.3
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.24,ghc-7.10.3,happy-1.19.5,alex-3.1.7]}}
     - env: CABALVER=1.24 GHCVER=8.0.1
-      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.7]}}
     - env: CABALVER=head GHCVER=head
-      addons: {apt: {packages: [cabal-install-head,ghc-head,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}
+      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.7]}}
 
   allow_failures:
     - env: CABALVER=head GHCVER=head
 
 before_install:
- - unset CC
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - export PATH=/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
+  - env
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
 
 install:
- - cabal --version
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
-   then
-     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
-          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
-   fi
- - travis_retry cabal update -v
- - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
- - cabal sandbox init
- - git clone https://github.com/emilaxelsson/imperative-edsl
- - git clone https://github.com/markus-git/hardware-edsl
- - cabal sandbox add-source imperative-edsl/
- - cabal sandbox add-source hardware-edsl/
- - cabal install --only-dependencies --enable-tests --enable-benchmarks --constraint="language-c-quote -full-haskell-antiquotes"
+  - cabal --version
+  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - travis_retry cabal update -v
+  - git clone https://github.com/emilaxelsson/imperative-edsl
+  #- git clone https://github.com/markus-git/hardware-edsl
+  - echo "packages:"         >  cabal.project &&
+    echo "  ./"              >> cabal.project &&
+    echo "  imperative-edsl" >> cabal.project
+    #&& echo "  hardware-edsl"   >> cabal.project
+  - cabal new-build --enable-tests --enable-benchmarks --constraint="language-c-quote -full-haskell-antiquotes" --dependencies
 
-# check whether current requested install-plan matches cached package-db snapshot
-#  - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
-#    then
-#      echo "cabal build-cache HIT";
-#      rm -rfv .ghc;
-#      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
-#      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-#    else
-#      echo "cabal build-cache MISS";
-#      rm -rf $HOME/.cabsnap;
-#      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
-#      cabal install --only-dependencies --enable-tests --enable-benchmarks;
-#    fi
-
-# snapshot package-db on cache miss
-#  - if [ ! -d $HOME/.cabsnap ];
-#    then
-#       echo "snapshotting package-db to build-cache";
-#       mkdir $HOME/.cabsnap;
-#       cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
-#       cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
-#    fi
-
-# Here starts the actual work to be performed for the package under test;
-# any command which exits with a non-zero exit code causes the build to fail.
 script:
- - if [ -f configure.ac ]; then autoreconf -i; fi
- - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
- - cabal build   # this builds all libraries and executables (including tests/benchmarks)
- - cabal test
- - cabal check
- - cabal sdist   # tests that a source-distribution can be generated
+  - cabal new-build --enable-tests --enable-benchmarks --constraint="language-c-quote -full-haskell-antiquotes" -v2 test:NumSimpl
+  - TESTS=( $(awk 'tolower($0) ~ /^test-suite / { print $2 }' *.cabal) );
+    RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+    if dist-newstyle/build/*/build/$T/$T; then echo "= $T OK =";
+    else echo "= $T FAILED ="; RC=false; fi; done; $RC
+  - ls dist-newstyle/build/
+  - cabal check
+  - cabal sdist
+  # Check that the resulting source distribution can be built
+  - SRC_BASENAME=$(cabal info . | awk '{print $2;exit}')
+  - tar -C dist/ -xf dist/$SRC_BASENAME.tar.gz
+  - echo "packages:"               >  dist/$SRC_BASENAME/cabal.project &&
+    echo "  *.cabal"               >> dist/$SRC_BASENAME/cabal.project &&
+    echo "  ../../imperative-edsl" >> dist/$SRC_BASENAME/cabal.project
+  - cd dist/$SRC_BASENAME/
+  - cabal new-build --enable-tests --enable-benchmarks --constraint="language-c-quote -full-haskell-antiquotes" --disable-optimization
 
-# Check that the resulting source distribution can be built & installed.
-# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
-# `cabal install --force-reinstalls dist/*-*.tar.gz`
- - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
-   (cd dist && cabal sandbox init --sandbox=../.cabal-sandbox && cabal install --force-reinstalls "$SRC_TGZ")
-
-# EOF
